services:
  gateway:
    build:
      context: .
    image: maven/builder:gateway
    container_name: gateway
    ports:
      - "8080:8080"
    volumes:
      - "./src:/build/src"
      - "./target:/build/target:cached"
    command: "mvn spring-boot:run"
    networks:
      - my-application-network

  postgres-gateway:
    image: postgres
    container_name: postgres-gateway
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gateway
      POSTGRES_PASSWORD: gateway
      POSTGRES_DB: revoked_tokens
    networks: # allows containers to recognize the hostnames of other containers
      - my-application-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    networks: # allows containers to recognize the hostnames of other containers
      - my-application-network
networks:
  my-application-network:
    driver: bridge